name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  run-tests:
    name: Run test cases
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: [1.17, 1.16]
        exclude:
          - os: macos-latest
            go: 1.16

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: |
          make integration
          make integration_w_race
